//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande.generic;

import android.content.Context;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class FileHandler_
    extends FileHandler
{

    private Context context_;
    private static FileHandler_ instance_;

    private FileHandler_(Context context) {
        super(context);
        context_ = context;
    }

    public static FileHandler_ getInstance_(Context context) {
        if (instance_ == null) {
            OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
            instance_ = new FileHandler_(context.getApplicationContext());
            instance_.init_();
            OnViewChangedNotifier.replaceNotifier(previousNotifier);
        }
        return instance_;
    }

    private void init_() {
        context = context_;
        file = FileUtils_.getInstance_(context_);
    }

}
