//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande.generic;

import android.content.Context;
import com.movitech.grande.MainApp_;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class ImageUtils_
    extends ImageUtils
{

    private Context context_;
    private static ImageUtils_ instance_;

    private ImageUtils_(Context context) {
        context_ = context;
    }

    public static ImageUtils_ getInstance_(Context context) {
        if (instance_ == null) {
            OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
            instance_ = new ImageUtils_(context.getApplicationContext());
            instance_.init_();
            OnViewChangedNotifier.replaceNotifier(previousNotifier);
        }
        return instance_;
    }

    private void init_() {
        mApp = MainApp_.getInstance();
        context = context_;
        fileHandler = FileHandler_.getInstance_(context_);
        network = NetworkUtils_.getInstance_(context_);
        file = FileUtils_.getInstance_(context_);
        mSDCard = SDCard_.getInstance_(context_);
    }

}
