//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande.generic;

import android.content.Context;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class JsonUtils_
    extends JsonUtils
{

    private Context context_;
    private static JsonUtils_ instance_;

    private JsonUtils_(Context context) {
        context_ = context;
    }

    public static JsonUtils_ getInstance_(Context context) {
        if (instance_ == null) {
            OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
            instance_ = new JsonUtils_(context.getApplicationContext());
            instance_.init_();
            OnViewChangedNotifier.replaceNotifier(previousNotifier);
        }
        return instance_;
    }

    private void init_() {
    }

}
