//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande.generic;

import android.content.Context;

public final class SDCard_
    extends SDCard
{

    private Context context_;

    private SDCard_(Context context) {
        context_ = context;
        init_();
    }

    public static SDCard_ getInstance_(Context context) {
        return new SDCard_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
