//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande;

import com.movitech.grande.generic.ImageUtils_;
import com.movitech.grande.sp.UserSP_;

public final class MainApp_
    extends MainApp
{

    private static MainApp INSTANCE_;

    public static MainApp getInstance() {
        return INSTANCE_;
    }

    /**
     * Visible for testing purposes
     * 
     */
    public static void setForTesting(MainApp application) {
        INSTANCE_ = application;
    }

    @Override
    public void onCreate() {
        INSTANCE_ = this;
        init_();
        super.onCreate();
    }

    private void init_() {
        userSP = new UserSP_(this);
        imageUtils = ImageUtils_.getInstance_(this);
    }

}
