//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande;

import android.app.NotificationManager;
import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;
import android.support.v4.app.Fragment;
import com.movitech.grande.net.NetHandler_;

public final class PushService_
    extends PushService
{


    public static PushService_.IntentBuilder_ intent(Context context) {
        return new PushService_.IntentBuilder_(context);
    }

    public static PushService_.IntentBuilder_ intent(Fragment supportFragment) {
        return new PushService_.IntentBuilder_(supportFragment);
    }

    private void init_() {
        notificationManager = ((NotificationManager) this.getSystemService(Context.NOTIFICATION_SERVICE));
        mApp = MainApp_.getInstance();
        netHandler = NetHandler_.getInstance_(this);
    }

    @Override
    public void onCreate() {
        init_();
        super.onCreate();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, PushService_.class);
        }

        public IntentBuilder_(Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, PushService_.class);
        }

        public Intent get() {
            return intent_;
        }

        public PushService_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public ComponentName start() {
            return context_.startService(intent_);
        }

        public boolean stop() {
            return context_.stopService(intent_);
        }

    }

}
