//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande.net;

import android.content.Context;
import com.movitech.grande.MainApp_;
import com.movitech.grande.generic.JsonUtils_;
import com.movitech.grande.net.client.AddSubInstClient_;
import com.movitech.grande.net.client.AppointmentClient_;
import com.movitech.grande.net.client.BrokerDetailClient_;
import com.movitech.grande.net.client.CancelFavBuildClient_;
import com.movitech.grande.net.client.CertificationClient_;
import com.movitech.grande.net.client.CitiesClient_;
import com.movitech.grande.net.client.ClientSearchClient_;
import com.movitech.grande.net.client.CommissionApplyClient_;
import com.movitech.grande.net.client.CommissionClient_;
import com.movitech.grande.net.client.CommissionConfirmClient_;
import com.movitech.grande.net.client.CustomerDetailClient_;
import com.movitech.grande.net.client.DayMarkClient_;
import com.movitech.grande.net.client.DistrictsClient_;
import com.movitech.grande.net.client.EarnIntegralClient_;
import com.movitech.grande.net.client.FavBuildClient_;
import com.movitech.grande.net.client.FocusBuildClient_;
import com.movitech.grande.net.client.ForgetPassWordClient_;
import com.movitech.grande.net.client.GuestIdClient_;
import com.movitech.grande.net.client.HouseBannerClient_;
import com.movitech.grande.net.client.HousesClient_;
import com.movitech.grande.net.client.HousesDetailClient_;
import com.movitech.grande.net.client.HuStyleClient_;
import com.movitech.grande.net.client.ImageClient_;
import com.movitech.grande.net.client.InfoBannerClient_;
import com.movitech.grande.net.client.InfoDetailClient_;
import com.movitech.grande.net.client.InfoesClient_;
import com.movitech.grande.net.client.IntegralClient_;
import com.movitech.grande.net.client.IsCollectClient_;
import com.movitech.grande.net.client.MyCustomerClient_;
import com.movitech.grande.net.client.MyMessageClient_;
import com.movitech.grande.net.client.MyUnreadCountClient_;
import com.movitech.grande.net.client.NewsLatestClient_;
import com.movitech.grande.net.client.OrgBrokerDetailClient_;
import com.movitech.grande.net.client.PushMessageClient_;
import com.movitech.grande.net.client.QQBindClient_;
import com.movitech.grande.net.client.QQIsBindClient_;
import com.movitech.grande.net.client.ReNameClient_;
import com.movitech.grande.net.client.RePasswardClient_;
import com.movitech.grande.net.client.RecommendedClient_;
import com.movitech.grande.net.client.RegClient_;
import com.movitech.grande.net.client.RuleBannerClient_;
import com.movitech.grande.net.client.ServiceTermsClient_;
import com.movitech.grande.net.client.ShareIntegralClient_;
import com.movitech.grande.net.client.SubOrgStatusClient_;
import com.movitech.grande.net.client.TeamClient_;
import com.movitech.grande.net.client.UserLoginClient_;
import com.movitech.grande.net.client.VerificationCodeClient_;
import com.movitech.grande.net.client.VersionClient_;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class NetHandler_
    extends NetHandler
{

    private Context context_;
    private static NetHandler_ instance_;

    private NetHandler_(Context context) {
        context_ = context;
    }

    public static NetHandler_ getInstance_(Context context) {
        if (instance_ == null) {
            OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
            instance_ = new NetHandler_(context.getApplicationContext());
            instance_.init_();
            OnViewChangedNotifier.replaceNotifier(previousNotifier);
        }
        return instance_;
    }

    private void init_() {
        mApp = MainApp_.getInstance();
        myMessageClient = new MyMessageClient_();
        mRePasswardClient = new RePasswardClient_();
        dayMarkClient = new DayMarkClient_();
        houseBannerClient = new HouseBannerClient_();
        commissionApplyClient = new CommissionApplyClient_();
        pushMessageClient = new PushMessageClient_();
        mHousesClient = new HousesClient_();
        mCustomerDetailClient = new CustomerDetailClient_();
        qqBindClient = new QQBindClient_();
        imageClient = new ImageClient_();
        mCertificationClient = new CertificationClient_();
        appointmentClient = new AppointmentClient_();
        subOrgStatusClient = new SubOrgStatusClient_();
        clientSearchClient = new ClientSearchClient_();
        myUnreadCountClient = new MyUnreadCountClient_();
        serviceTermsClient = new ServiceTermsClient_();
        qqIsBindClient = new QQIsBindClient_();
        forgetPassWordClient = new ForgetPassWordClient_();
        focusBuildClient = new FocusBuildClient_();
        guestIdClient = new GuestIdClient_();
        huStyleClient = new HuStyleClient_();
        mCommissionClient = new CommissionClient_();
        recommendedClient = new RecommendedClient_();
        earnIntegralClient = new EarnIntegralClient_();
        mInfoDetailClient = new InfoDetailClient_();
        myCustomerClient = new MyCustomerClient_();
        regClient = new RegClient_();
        shareIntegralClient = new ShareIntegralClient_();
        brokerDetailClient = new BrokerDetailClient_();
        confirmClient = new CommissionConfirmClient_();
        ruleBannerClient = new RuleBannerClient_();
        teamClient = new TeamClient_();
        cancelFavBuildClient = new CancelFavBuildClient_();
        isCollectClient = new IsCollectClient_();
        infoBannerClient = new InfoBannerClient_();
        mIntegralClient = new IntegralClient_();
        mInfoesClient = new InfoesClient_();
        newsLatestClient = new NewsLatestClient_();
        addSubInstClient = new AddSubInstClient_();
        mDistrictsClient = new DistrictsClient_();
        mCitysClient = new CitiesClient_();
        orgBrokerdetailClient = new OrgBrokerDetailClient_();
        mHousesDetailClient = new HousesDetailClient_();
        mUserLoginClient = new UserLoginClient_();
        verificationCodeClient = new VerificationCodeClient_();
        favBuildClient = new FavBuildClient_();
        versionClient = new VersionClient_();
        mReNameClient = new ReNameClient_();
        mContext = context_;
        jsonUtils = JsonUtils_.getInstance_(context_);
    }

}
