//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande.image;

import android.content.Context;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class FileUtils_
    extends FileUtils
{

    private Context context_;
    private static FileUtils_ instance_;

    private FileUtils_(Context context) {
        super(context);
        context_ = context;
    }

    public static FileUtils_ getInstance_(Context context) {
        if (instance_ == null) {
            OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
            instance_ = new FileUtils_(context.getApplicationContext());
            instance_.init_();
            OnViewChangedNotifier.replaceNotifier(previousNotifier);
        }
        return instance_;
    }

    private void init_() {
    }

}
