//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.support.v4.app.Fragment;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.movitech.grande.MainApp_;
import com.movitech.grande.haerbin.R.id;
import com.movitech.grande.haerbin.R.layout;
import com.movitech.grande.net.NetHandler_;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.SdkVersionHelper;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class ForgetPasswordActivity_
    extends ForgetPasswordActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_forget_password);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        mApp = MainApp_.getInstance();
        netHandler = NetHandler_.getInstance_(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ForgetPasswordActivity_.IntentBuilder_ intent(Context context) {
        return new ForgetPasswordActivity_.IntentBuilder_(context);
    }

    public static ForgetPasswordActivity_.IntentBuilder_ intent(Fragment supportFragment) {
        return new ForgetPasswordActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        rlFirstStep = ((RelativeLayout) hasViews.findViewById(id.rl_first_step));
        llSendAuthCode = ((LinearLayout) hasViews.findViewById(id.ll_send_auth_code));
        edtNewPasswordAgain = ((EditText) hasViews.findViewById(id.edt_new_password_again));
        btnPasswordComplete = ((Button) hasViews.findViewById(id.btn_password_complete));
        edtForgetPhone = ((EditText) hasViews.findViewById(id.edt_forget_phone));
        rlComplete = ((RelativeLayout) hasViews.findViewById(id.rl_complete));
        txtSendAuthCode = ((TextView) hasViews.findViewById(id.txt_send_auth_code));
        btnNextStep = ((Button) hasViews.findViewById(id.btn_next_step));
        edtForgetCode = ((EditText) hasViews.findViewById(id.edt_forget_code));
        ivBack = ((ImageView) hasViews.findViewById(id.iv_back));
        edtForgetNewPassword = ((EditText) hasViews.findViewById(id.edt_forget_new_password));
        {
            View view = hasViews.findViewById(id.btn_next_step);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ForgetPasswordActivity_.this.btnNextStep();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.btn_password_complete);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ForgetPasswordActivity_.this.btnPasswordComplete();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.iv_back);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ForgetPasswordActivity_.this.ivBack();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.ll_send_auth_code);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ForgetPasswordActivity_.this.llSendAuthCode();
                    }

                }
                );
            }
        }
        afterViews();
    }

    @Override
    public void changeNumber() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                ForgetPasswordActivity_.super.changeNumber();
            }

        }
        );
    }

    @Override
    public void goBackMainThreadCode(final String msg, final boolean success) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                ForgetPasswordActivity_.super.goBackMainThreadCode(msg, success);
            }

        }
        );
    }

    @Override
    public void doDataBind() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                ForgetPasswordActivity_.super.doDataBind();
            }

        }
        );
    }

    @Override
    public void complete() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                ForgetPasswordActivity_.super.complete();
            }

        }
        );
    }

    @Override
    public void doSendNewPassWord() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    ForgetPasswordActivity_.super.doSendNewPassWord();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void doSendMessage() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    ForgetPasswordActivity_.super.doSendMessage();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void checkTheCode() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    ForgetPasswordActivity_.super.checkTheCode();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ForgetPasswordActivity_.class);
        }

        public IntentBuilder_(Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, ForgetPasswordActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ForgetPasswordActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (context_ instanceof Activity) {
                    ((Activity) context_).startActivityForResult(intent_, requestCode);
                } else {
                    context_.startActivity(intent_);
                }
            }
        }

    }

}
