//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.support.v4.app.Fragment;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.movitech.grande.MainApp_;
import com.movitech.grande.haerbin.R.id;
import com.movitech.grande.haerbin.R.layout;
import com.movitech.grande.net.NetHandler_;
import com.movitech.grande.sp.LoginSP_;
import com.movitech.grande.sp.UserSP_;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.SdkVersionHelper;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class LoginActivity_
    extends LoginActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_login);
    }

    private void init_(Bundle savedInstanceState) {
        userSP = new UserSP_(this);
        loginSP = new LoginSP_(this);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        mApp = MainApp_.getInstance();
        netHandler = NetHandler_.getInstance_(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static LoginActivity_.IntentBuilder_ intent(Context context) {
        return new LoginActivity_.IntentBuilder_(context);
    }

    public static LoginActivity_.IntentBuilder_ intent(Fragment supportFragment) {
        return new LoginActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        rlLoginQqBtn = ((RelativeLayout) hasViews.findViewById(id.rl_login_qq_btn));
        ivLoginUsername = ((ImageView) hasViews.findViewById(id.iv_login_username));
        rlLoginRegister = ((RelativeLayout) hasViews.findViewById(id.rl_login_register));
        rlUserImage = ((RelativeLayout) hasViews.findViewById(id.rl_user_image));
        edtLoginPassword = ((EditText) hasViews.findViewById(id.edt_login_password));
        ivBack = ((ImageView) hasViews.findViewById(id.iv_back));
        rlLoginPassword = ((RelativeLayout) hasViews.findViewById(id.rl_login_password));
        rlBottom = ((RelativeLayout) hasViews.findViewById(id.rl_bottom));
        ivLoginMore = ((ImageView) hasViews.findViewById(id.iv_login_more));
        edtLoginUsername = ((EditText) hasViews.findViewById(id.edt_login_username));
        rlTop = ((RelativeLayout) hasViews.findViewById(id.rl_top));
        rlLoginAccount = ((RelativeLayout) hasViews.findViewById(id.rl_login_account));
        ivUserImage = ((ImageView) hasViews.findViewById(id.iv_user_image));
        tvLoginQq = ((TextView) hasViews.findViewById(id.tv_login_qq));
        rlLoginBtn = ((RelativeLayout) hasViews.findViewById(id.rl_login_btn));
        ivLoginPassword = ((ImageView) hasViews.findViewById(id.iv_login_password));
        ivLoginQq = ((ImageView) hasViews.findViewById(id.iv_login_qq));
        rlLoginPasswordForget = ((RelativeLayout) hasViews.findViewById(id.rl_login_password_forget));
        rlLoginQq = ((RelativeLayout) hasViews.findViewById(id.rl_login_qq));
        ivLoginPasswordForget = ((ImageView) hasViews.findViewById(id.iv_login_password_forget));
        {
            View view = hasViews.findViewById(id.rl_login_qq);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        LoginActivity_.this.rlLoginQq();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.rl_login_btn);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        LoginActivity_.this.rlLoginBtn();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.rl_login_password_forget);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        LoginActivity_.this.rlLoginPasswordForget();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.iv_back);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        LoginActivity_.this.ivBack();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.rl_login_register);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        LoginActivity_.this.rlLoginRegister();
                    }

                }
                );
            }
        }
        afterViews();
    }

    @Override
    public void goBackMainThread(final String msg, final boolean success) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                LoginActivity_.super.goBackMainThread(msg, success);
            }

        }
        );
    }

    @Override
    public void goBackMainQQThread(final String resultMsg, final boolean success) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                LoginActivity_.super.goBackMainQQThread(resultMsg, success);
            }

        }
        );
    }

    @Override
    public void doLoadIsBindQQ(final String token) {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    LoginActivity_.super.doLoadIsBindQQ(token);
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void access(final String username, final String password) {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("task", 0, "") {


            @Override
            public void execute() {
                try {
                    LoginActivity_.super.access(username, password);
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, LoginActivity_.class);
        }

        public IntentBuilder_(Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, LoginActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public LoginActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (context_ instanceof Activity) {
                    ((Activity) context_).startActivityForResult(intent_, requestCode);
                } else {
                    context_.startActivity(intent_);
                }
            }
        }

    }

}
