//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.support.v4.app.Fragment;
import android.support.v4.view.ViewPager;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.movitech.grande.MainApp_;
import com.movitech.grande.haerbin.R.id;
import com.movitech.grande.haerbin.R.layout;
import com.movitech.grande.net.NetHandler_;
import com.movitech.grande.net.protocol.XcfcVersionResult;
import com.movitech.grande.sp.NewsSP_;
import com.movitech.grande.sp.UserSP_;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.SdkVersionHelper;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class MainActivity_
    extends MainActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_main);
    }

    private void init_(Bundle savedInstanceState) {
        userSP = new UserSP_(this);
        newsSP = new NewsSP_(this);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        mApp = MainApp_.getInstance();
        netHandler = NetHandler_.getInstance_(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static MainActivity_.IntentBuilder_ intent(Context context) {
        return new MainActivity_.IntentBuilder_(context);
    }

    public static MainActivity_.IntentBuilder_ intent(Fragment supportFragment) {
        return new MainActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        ivHouses = ((ImageView) hasViews.findViewById(id.iv_houses));
        rlMine = ((RelativeLayout) hasViews.findViewById(id.rl_mine));
        txtRecom = ((TextView) hasViews.findViewById(id.txt_recom));
        rlInfo = ((RelativeLayout) hasViews.findViewById(id.rl_info));
        ivInfoIndicator = ((ImageView) hasViews.findViewById(id.iv_info_indicator));
        llBottom = ((LinearLayout) hasViews.findViewById(id.ll_bottom));
        ivRecom = ((ImageView) hasViews.findViewById(id.iv_recom));
        rlHouses = ((RelativeLayout) hasViews.findViewById(id.rl_houses));
        ivRecomIndicator = ((ImageView) hasViews.findViewById(id.iv_recom_indicator));
        txtTeam = ((TextView) hasViews.findViewById(id.txt_team));
        rlTeam = ((RelativeLayout) hasViews.findViewById(id.rl_team));
        rlRecom = ((RelativeLayout) hasViews.findViewById(id.rl_recom));
        txtInfo = ((TextView) hasViews.findViewById(id.txt_info));
        ivInfo = ((ImageView) hasViews.findViewById(id.iv_info));
        viewPager = ((ViewPager) hasViews.findViewById(id.view_pager));
        txtHouses = ((TextView) hasViews.findViewById(id.txt_houses));
        ivHousesIndicator = ((ImageView) hasViews.findViewById(id.iv_houses_indicator));
        ivTeam = ((ImageView) hasViews.findViewById(id.iv_team));
        txtMine = ((TextView) hasViews.findViewById(id.txt_mine));
        ivMine = ((ImageView) hasViews.findViewById(id.iv_mine));
        ivMineIndicator = ((ImageView) hasViews.findViewById(id.iv_mine_indicator));
        {
            View view = hasViews.findViewById(id.rl_houses);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.rlHouses();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.rl_recom);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.rlRecom();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.rl_mine);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.rlMine();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.rl_info);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.rlInfo();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.rl_team);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MainActivity_.this.rlTeam();
                    }

                }
                );
            }
        }
        afterViews();
    }

    @Override
    public void goBackMainThreadUpdate(final XcfcVersionResult result) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                MainActivity_.super.goBackMainThreadUpdate(result);
            }

        }
        );
    }

    @Override
    public void setUnreadUi(final boolean hasNewsNewCity, final boolean hasNewsHouse) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                MainActivity_.super.setUnreadUi(hasNewsNewCity, hasNewsHouse);
            }

        }
        );
    }

    @Override
    public void setMyMessageUnreadUi(final String count) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                MainActivity_.super.setMyMessageUnreadUi(count);
            }

        }
        );
    }

    @Override
    public void initUnread() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    MainActivity_.super.initUnread();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void setMyMessageIndicator() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    MainActivity_.super.setMyMessageIndicator();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void checkVersionFromServer() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    MainActivity_.super.checkVersionFromServer();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, MainActivity_.class);
        }

        public IntentBuilder_(Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, MainActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public MainActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (context_ instanceof Activity) {
                    ((Activity) context_).startActivityForResult(intent_, requestCode);
                } else {
                    context_.startActivity(intent_);
                }
            }
        }

    }

}
