//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.support.v4.app.Fragment;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.movitech.grande.MainApp_;
import com.movitech.grande.generic.ImageUtils_;
import com.movitech.grande.haerbin.R.id;
import com.movitech.grande.haerbin.R.layout;
import com.movitech.grande.net.NetHandler_;
import com.movitech.grande.sp.UserSP_;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.SdkVersionHelper;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class MineSettingActivity_
    extends MineSettingActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_mine_setting);
    }

    private void init_(Bundle savedInstanceState) {
        userSP = new UserSP_(this);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        mApp = MainApp_.getInstance();
        imageUtils = ImageUtils_.getInstance_(this);
        netHandler = NetHandler_.getInstance_(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static MineSettingActivity_.IntentBuilder_ intent(Context context) {
        return new MineSettingActivity_.IntentBuilder_(context);
    }

    public static MineSettingActivity_.IntentBuilder_ intent(Fragment supportFragment) {
        return new MineSettingActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        tvRealNameCerti = ((TextView) hasViews.findViewById(id.tv_real_name_certi));
        btnLoginExit = ((Button) hasViews.findViewById(id.btn_login_exit));
        rlMySettingCertification = ((RelativeLayout) hasViews.findViewById(id.rl_my_setting_certification));
        tvNickname = ((TextView) hasViews.findViewById(id.tv_nickname));
        txtMyName = ((TextView) hasViews.findViewById(id.txt_my_name));
        rlMySettingName = ((RelativeLayout) hasViews.findViewById(id.rl_my_setting_name));
        ivBack = ((ImageView) hasViews.findViewById(id.iv_back));
        rlMySettingPassword = ((RelativeLayout) hasViews.findViewById(id.rl_my_setting_password));
        mySettingCard = ((RelativeLayout) hasViews.findViewById(id.rl_my_setting_card));
        rlPersonalPhoto = ((RelativeLayout) hasViews.findViewById(id.rl_personal_photo));
        rlTop = ((RelativeLayout) hasViews.findViewById(id.rl_top));
        ivUserImage = ((ImageView) hasViews.findViewById(id.iv_user_image));
        {
            View view = hasViews.findViewById(id.btn_login_exit);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MineSettingActivity_.this.btnLoginExit();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.rl_my_setting_card);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MineSettingActivity_.this.rlMySettingCard();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.rl_my_setting_name);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MineSettingActivity_.this.rlMySettingName();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.iv_back);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MineSettingActivity_.this.ivBack();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.rl_my_setting_password);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MineSettingActivity_.this.rlMySettingPassword();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.rl_personal_photo);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MineSettingActivity_.this.rlPersonalPhoto();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.rl_my_setting_certification);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MineSettingActivity_.this.rlMySettingCertification();
                    }

                }
                );
            }
        }
        afterViews();
    }

    @Override
    public void exitBackMainThread(final boolean success) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                MineSettingActivity_.super.exitBackMainThread(success);
            }

        }
        );
    }

    @Override
    public void finishUploadImage(final String msg, final boolean success) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                MineSettingActivity_.super.finishUploadImage(msg, success);
            }

        }
        );
    }

    @Override
    public void getGuestIdFromServer() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    MineSettingActivity_.super.getGuestIdFromServer();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void uploadHeader(final String filePath) {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    MineSettingActivity_.super.uploadHeader(filePath);
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, MineSettingActivity_.class);
        }

        public IntentBuilder_(Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, MineSettingActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public MineSettingActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (context_ instanceof Activity) {
                    ((Activity) context_).startActivityForResult(intent_, requestCode);
                } else {
                    context_.startActivity(intent_);
                }
            }
        }

    }

}
