//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.support.v4.app.Fragment;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.movitech.grande.MainApp_;
import com.movitech.grande.haerbin.R.layout;
import com.movitech.grande.net.NetHandler_;
import com.movitech.grande.views.BaseViewPager;
import com.movitech.grande.views.UnderlinePageIndicator;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.SdkVersionHelper;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class MyCommissionActivity_
    extends MyCommissionActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_my_commission);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        mApp = MainApp_.getInstance();
        netHandler = NetHandler_.getInstance_(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static MyCommissionActivity_.IntentBuilder_ intent(Context context) {
        return new MyCommissionActivity_.IntentBuilder_(context);
    }

    public static MyCommissionActivity_.IntentBuilder_ intent(Fragment supportFragment) {
        return new MyCommissionActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        rlCommissionWait = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_commission_wait));
        txtCommissionGrant = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_commission_grant));
        ivBack = ((ImageView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.iv_back));
        vpFragmentCommission = ((BaseViewPager) hasViews.findViewById(com.movitech.grande.haerbin.R.id.vp_fragment_commission));
        txtCommissionOk = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_commission_ok));
        rlCommissionGrant = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_commission_grant));
        indicatorFragmentCommission = ((UnderlinePageIndicator) hasViews.findViewById(com.movitech.grande.haerbin.R.id.indicator_fragment_commission));
        txtCommissionWait = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_commission_wait));
        rlCommissionOk = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_commission_ok));
        {
            View view = hasViews.findViewById(com.movitech.grande.haerbin.R.id.iv_back);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MyCommissionActivity_.this.ivBack();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_commission_grant);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MyCommissionActivity_.this.rlCommissionGrant();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_commission_ok);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MyCommissionActivity_.this.rlCommissionOk();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_commission_wait);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MyCommissionActivity_.this.rlCommissionWait();
                    }

                }
                );
            }
        }
        afterViews();
    }

    @Override
    public void doBindDataApplyCommission() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                MyCommissionActivity_.super.doBindDataApplyCommission();
            }

        }
        );
    }

    @Override
    public void doBindAndDataConfirm() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                MyCommissionActivity_.super.doBindAndDataConfirm();
            }

        }
        );
    }

    @Override
    public void doBindData(final int currentPage) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                MyCommissionActivity_.super.doBindData(currentPage);
            }

        }
        );
    }

    @Override
    public void doLoadDataAndBindData(final int pageNo, final String id, final String status) {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    MyCommissionActivity_.super.doLoadDataAndBindData(pageNo, id, status);
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void doLoadCommissionConfirmData(final String brokerId, final String id) {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    MyCommissionActivity_.super.doLoadCommissionConfirmData(brokerId, id);
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void doLoadCommissionApplyData(final String brokerId, final String[] id) {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    MyCommissionActivity_.super.doLoadCommissionApplyData(brokerId, id);
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, MyCommissionActivity_.class);
        }

        public IntentBuilder_(Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, MyCommissionActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public MyCommissionActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (context_ instanceof Activity) {
                    ((Activity) context_).startActivityForResult(intent_, requestCode);
                } else {
                    context_.startActivity(intent_);
                }
            }
        }

    }

}
