//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande.activity;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.movitech.grande.MainApp_;
import com.movitech.grande.haerbin.R.id;
import com.movitech.grande.haerbin.R.layout;
import com.movitech.grande.net.NetHandler_;
import com.movitech.grande.views.BaseViewPager;
import com.movitech.grande.views.CustomHorizontalScrollView;
import com.movitech.grande.views.UnderlinePageIndicator;
import org.androidannotations.api.SdkVersionHelper;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class MyCustomerActivity_
    extends MyCustomerActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_my_customer);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        mApp = MainApp_.getInstance();
        netHandler = NetHandler_.getInstance_(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static MyCustomerActivity_.IntentBuilder_ intent(Context context) {
        return new MyCustomerActivity_.IntentBuilder_(context);
    }

    public static MyCustomerActivity_.IntentBuilder_ intent(Fragment supportFragment) {
        return new MyCustomerActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        ivSearch = ((ImageView) hasViews.findViewById(id.iv_search));
        rlTagCustomerSeaHouse = ((RelativeLayout) hasViews.findViewById(id.rl_tag_customer_sea_house));
        rlSearchClient = ((RelativeLayout) hasViews.findViewById(id.rl_search_client));
        rlTagCustomerImportant = ((RelativeLayout) hasViews.findViewById(id.rl_tag_customer_important));
        ivBack = ((ImageView) hasViews.findViewById(id.iv_back));
        rlTagCustomerRecommendedConfirm = ((RelativeLayout) hasViews.findViewById(id.rl_tag_customer_recommended_confirm));
        txtTagCustomerSeaHouse = ((TextView) hasViews.findViewById(id.txt_tag_customer_sea_house));
        txtTagCustomerRecommendedOk = ((TextView) hasViews.findViewById(id.txt_tag_customer_recommended_ok));
        vpCustomerType = ((BaseViewPager) hasViews.findViewById(id.vp_customer_type));
        svTop = ((CustomHorizontalScrollView) hasViews.findViewById(id.sv_top));
        rlTagCustomerRecommendedOk = ((RelativeLayout) hasViews.findViewById(id.rl_tag_customer_recommended_ok));
        rlTagCustomerSales = ((RelativeLayout) hasViews.findViewById(id.rl_tag_customer_sales));
        ivNavigatorLeft = ((ImageView) hasViews.findViewById(id.iv_navigator_left));
        txtTagCustomerImportant = ((TextView) hasViews.findViewById(id.txt_tag_customer_important));
        ivNavigatorRight = ((ImageView) hasViews.findViewById(id.iv_navigator_right));
        indicatorCustomerType = ((UnderlinePageIndicator) hasViews.findViewById(id.indicator_customer_type));
        txtTagCustomerRecommendedConfirm = ((TextView) hasViews.findViewById(id.txt_tag_customer_recommended_confirm));
        txtTagCustomerSales = ((TextView) hasViews.findViewById(id.txt_tag_customer_sales));
        {
            View view = hasViews.findViewById(id.iv_navigator_left);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MyCustomerActivity_.this.ivNavigatorLeft();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.iv_back);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MyCustomerActivity_.this.ivBack();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.rl_tag_customer_recommended_ok);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MyCustomerActivity_.this.rlTagCustomerRecommendedOk();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.rl_tag_customer_sales);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MyCustomerActivity_.this.rlTagCustomerSales();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.rl_search_client);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MyCustomerActivity_.this.rlSearchClient();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.rl_tag_customer_recommended_confirm);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MyCustomerActivity_.this.rlTagCustomerRecommendedConfirm();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.rl_tag_customer_sea_house);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MyCustomerActivity_.this.rlTagCustomerSeaHouse();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.iv_navigator_right);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MyCustomerActivity_.this.ivNavigatorRight();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.rl_tag_customer_important);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MyCustomerActivity_.this.rlTagCustomerImportant();
                    }

                }
                );
            }
        }
        afterViews();
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, MyCustomerActivity_.class);
        }

        public IntentBuilder_(Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, MyCustomerActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public MyCustomerActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent_, requestCode);
            } else {
                if (context_ instanceof Activity) {
                    ((Activity) context_).startActivityForResult(intent_, requestCode);
                } else {
                    context_.startActivity(intent_);
                }
            }
        }

    }

}
