//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande.net.client;

import java.util.Collections;
import java.util.HashMap;
import com.movitech.grande.net.protocol.BaseResult;
import org.androidannotations.api.rest.RestErrorHandler;
import org.springframework.http.HttpAuthentication;
import org.springframework.http.HttpBasicAuthentication;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.http.converter.json.MappingJackson2HttpMessageConverter;
import org.springframework.util.MultiValueMap;
import org.springframework.web.client.RestClientException;
import org.springframework.web.client.RestTemplate;

public final class RegClient_
    implements RegClient
{

    private RestTemplate restTemplate;
    private HttpAuthentication authentication;
    private HashMap<String, String> availableCookies;
    private HashMap<String, String> availableHeaders;
    private RestErrorHandler restErrorHandler;
    private String rootUrl;

    public RegClient_() {
        restTemplate = new RestTemplate();
        availableCookies = new HashMap<String, String>();
        availableHeaders = new HashMap<String, String>();
        rootUrl = "";
        restTemplate.getMessageConverters().add(new MappingJackson2HttpMessageConverter());
    }

    @Override
    public RestTemplate getRestTemplate() {
        return restTemplate;
    }

    @Override
    public void setRestTemplate(RestTemplate arg0) {
        this.restTemplate = arg0;
    }

    @Override
    public void setHttpBasicAuth(String arg0, String arg1) {
        this.authentication = new HttpBasicAuthentication(arg0, arg1);
    }

    @Override
    public void setAuthentication(HttpAuthentication arg0) {
        this.authentication = arg0;
    }

    @Override
    public String getCookie(String arg0) {
        return availableCookies.get(arg0);
    }

    @Override
    public String getHeader(String arg0) {
        return availableHeaders.get(arg0);
    }

    @Override
    public void setCookie(String arg0, String arg1) {
        availableCookies.put(arg0, arg1);
    }

    @Override
    public void setHeader(String arg0, String arg1) {
        availableHeaders.put(arg0, arg1);
    }

    @Override
    public void setRestErrorHandler(RestErrorHandler arg0) {
        this.restErrorHandler = arg0;
    }

    @Override
    public BaseResult regBroker(String url, String userId, String clientName, String clientPhone, String qq, String weixin, String deviceId, String brokerType, String password, String city, String buildId) {
        HttpHeaders httpHeaders = new HttpHeaders();
        httpHeaders.setAccept(Collections.singletonList(MediaType.parseMediaType("application/json")));
        httpHeaders.set("Content-Type", availableHeaders.get("Content-Type"));
        HttpEntity<Object> requestEntity = new HttpEntity<Object>(httpHeaders);
        HashMap<String, Object> urlVariables = new HashMap<String, Object>();
        urlVariables.put("weixin", weixin);
        urlVariables.put("buildId", buildId);
        urlVariables.put("clientPhone", clientPhone);
        urlVariables.put("clientName", clientName);
        urlVariables.put("userId", userId);
        urlVariables.put("brokerType", brokerType);
        urlVariables.put("password", password);
        urlVariables.put("deviceId", deviceId);
        urlVariables.put("qq", qq);
        urlVariables.put("url", url);
        urlVariables.put("city", city);
        try {
            return restTemplate.exchange(rootUrl.concat("{url}/rest/broker/addBroker?id={userId}&clientName={clientName}&clientPhone={clientPhone}&mqq={qq}&mweixin={weixin}&iosDevice=&androidDevice={deviceId}&brokerType={brokerType}&password={password}&city={city}&buildId={buildId}"), HttpMethod.GET, requestEntity, BaseResult.class, urlVariables).getBody();
        } catch (RestClientException e) {
            if (restErrorHandler!= null) {
                restErrorHandler.onRestClientExceptionThrown(e);
                return null;
            } else {
                throw e;
            }
        }
    }

    @Override
    public BaseResult postRegBroker(String url, MultiValueMap<String, String> params) {
        HttpHeaders httpHeaders = new HttpHeaders();
        httpHeaders.setAccept(Collections.singletonList(MediaType.parseMediaType("application/json")));
        httpHeaders.set("Content-Type", availableHeaders.get("Content-Type"));
        HttpEntity<MultiValueMap<String, String>> requestEntity = new HttpEntity<MultiValueMap<String, String>>(params, httpHeaders);
        HashMap<String, Object> urlVariables = new HashMap<String, Object>();
        urlVariables.put("url", url);
        try {
            return restTemplate.exchange(rootUrl.concat("{url}/rest/broker/addBroker"), HttpMethod.POST, requestEntity, BaseResult.class, urlVariables).getBody();
        } catch (RestClientException e) {
            if (restErrorHandler!= null) {
                restErrorHandler.onRestClientExceptionThrown(e);
                return null;
            } else {
                throw e;
            }
        }
    }

}
