//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande.fragment;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.movitech.grande.haerbin.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class HousesDetailToolFragment_
    extends HousesDetailToolFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_houses_detail_tool, container, false);
        }
        return contentView_;
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static HousesDetailToolFragment_.FragmentBuilder_ builder() {
        return new HousesDetailToolFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        ivHouseLoan = ((ImageView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.iv_house_loan));
        ivHousePrice = ((ImageView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.iv_house_price));
        rlHouseCity = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_house_city));
        rlHousePrice = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_house_price));
        txtHouseLoan = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_house_loan));
        txtHouseCity = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_house_city));
        rlHouseLoan = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_house_loan));
        ivHouseCity = ((ImageView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.iv_house_city));
        txtHousePrice = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_house_price));
        {
            View view = hasViews.findViewById(com.movitech.grande.haerbin.R.id.iv_house_loan);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HousesDetailToolFragment_.this.ivHouseLoan();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.movitech.grande.haerbin.R.id.iv_house_city);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HousesDetailToolFragment_.this.ivHouseCity();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.movitech.grande.haerbin.R.id.iv_house_price);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HousesDetailToolFragment_.this.ivHousePrice();
                    }

                }
                );
            }
        }
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public HousesDetailToolFragment build() {
            HousesDetailToolFragment_ fragment_ = new HousesDetailToolFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
