//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande.fragment;

import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.movitech.grande.MainApp_;
import com.movitech.grande.generic.ImageUtils_;
import com.movitech.grande.haerbin.R.layout;
import com.movitech.grande.views.AutoScaleTextView;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class HousesDetailMainPageFragment_
    extends HousesDetailMainPageFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_houses_detail_main_page, container, false);
        }
        return contentView_;
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        mApp = MainApp_.getInstance();
        imageUtils = ImageUtils_.getInstance_(getActivity());
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static HousesDetailMainPageFragment_.FragmentBuilder_ builder() {
        return new HousesDetailMainPageFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        rlHousesDetailBlock = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_houses_detail_block));
        txtTimeToOver = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_time_to_over));
        txtCommission = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_commission));
        rlPrivilegeLayoutRecommendHouses = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_privilege_layout_recommend_houses));
        txtAreaLayoutRecommendHouses = ((AutoScaleTextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_area_layout_recommend_houses));
        btnRecommendImmediately = ((Button) hasViews.findViewById(com.movitech.grande.haerbin.R.id.btn_recommend_immediately));
        rlMoreInfo = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_more_info));
        txtNameLayoutRecommendHouses = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_name_layout_recommend_houses));
        llRmbCommmission = ((LinearLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.ll_rmb_commmission));
        txtPrivilegeLayoutRecommendHouses = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_privilege_layout_recommend_houses));
        ivBackground = ((ImageView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.iv_background));
        txtPeopleAppointed = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_people_appointed));
        txtSectionLayoutRecommendHouses = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_section_layout_recommend_houses));
        ivPrivilegeRecommendHouses = ((ImageView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.iv_privilege_recommend_houses));
        txtTimesRecommended = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_times_recommended));
        rlHousesName = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_houses_name));
        btnHouseAppointment = ((Button) hasViews.findViewById(com.movitech.grande.haerbin.R.id.btn_house_appointment));
        {
            View view = hasViews.findViewById(com.movitech.grande.haerbin.R.id.btn_house_appointment);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HousesDetailMainPageFragment_.this.btnHouseAppointment();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.movitech.grande.haerbin.R.id.btn_recommend_immediately);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HousesDetailMainPageFragment_.this.btnRecommendImmediately();
                    }

                }
                );
            }
        }
        afterViews();
    }

    @Override
    public void doBindData() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                HousesDetailMainPageFragment_.super.doBindData();
            }

        }
        );
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public HousesDetailMainPageFragment build() {
            HousesDetailMainPageFragment_ fragment_ = new HousesDetailMainPageFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
