//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande.fragment;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.movitech.grande.generic.ImageUtils_;
import com.movitech.grande.haerbin.R.layout;
import com.movitech.grande.views.BaseViewPager;
import com.movitech.grande.views.UnderlinePageIndicator;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class HousesDetailTypeFragment_
    extends HousesDetailTypeFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_houses_detail_type, container, false);
        }
        return contentView_;
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        imageUtils = ImageUtils_.getInstance_(getActivity());
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static HousesDetailTypeFragment_.FragmentBuilder_ builder() {
        return new HousesDetailTypeFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        txtPicHousesType = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_pic_houses_type));
        txtPicHousesTraffic = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_pic_houses_traffic));
        indicatorFragmentInfo = ((UnderlinePageIndicator) hasViews.findViewById(com.movitech.grande.haerbin.R.id.indicator_fragment_info));
        rlPicHousesTraffic = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_pic_houses_traffic));
        llIndicateWords = ((LinearLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.ll_indicate_words));
        rlPicHousesSight = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_pic_houses_sight));
        rlPicHousesType = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_pic_houses_type));
        rlPicHousesEffect = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_pic_houses_effect));
        txtPicHousesSample = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_pic_houses_sample));
        rlPicHousesSample = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_pic_houses_sample));
        txtPicHousesSight = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_pic_houses_sight));
        vpFragmentInfo = ((BaseViewPager) hasViews.findViewById(com.movitech.grande.haerbin.R.id.vp_fragment_info));
        txtPicHousesEffect = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_pic_houses_effect));
        {
            View view = hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_pic_houses_sample);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HousesDetailTypeFragment_.this.rlPicHousesSample();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_pic_houses_sight);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HousesDetailTypeFragment_.this.rlPicHousesSight();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_pic_houses_traffic);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HousesDetailTypeFragment_.this.rlPicHousesTraffic();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_pic_houses_type);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HousesDetailTypeFragment_.this.rlPicHousesType();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_pic_houses_effect);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HousesDetailTypeFragment_.this.rlPicHousesEffect();
                    }

                }
                );
            }
        }
        afterViews();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public HousesDetailTypeFragment build() {
            HousesDetailTypeFragment_ fragment_ = new HousesDetailTypeFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
