//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande.fragment;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.movitech.grande.MainApp_;
import com.movitech.grande.haerbin.R.layout;
import com.movitech.grande.views.BaseViewPager;
import com.movitech.grande.views.UnderlinePageIndicator;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class InfoFragment_
    extends InfoFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_info, container, false);
        }
        return contentView_;
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        mApp = MainApp_.getInstance();
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static InfoFragment_.FragmentBuilder_ builder() {
        return new InfoFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        ivLeft = ((ImageView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.iv_left));
        rlMyMessages = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_my_messages));
        txtHousesActivities = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_houses_activities));
        rlHousesActivities = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_houses_activities));
        ivCenter = ((ImageView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.iv_center));
        txtNewcityActivities = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_newcity_activities));
        vpFragmentInfo = ((BaseViewPager) hasViews.findViewById(com.movitech.grande.haerbin.R.id.vp_fragment_info));
        txtMyMessages = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_my_messages));
        rlUnreadHousesActivities = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_unread_houses_activities));
        ivRight = ((ImageView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.iv_right));
        rlNewcityActivities = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_newcity_activities));
        rlUnreadMyMessages = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_unread_my_messages));
        indicatorFragmentInfo = ((UnderlinePageIndicator) hasViews.findViewById(com.movitech.grande.haerbin.R.id.indicator_fragment_info));
        txtUnread = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_unread));
        rlUnreadNewcityActivities = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_unread_newcity_activities));
        llIndicateWords = ((LinearLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.ll_indicate_words));
        txtUnreadMyMessages = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_unread_my_messages));
        txtUnreadNewcityActivities = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_unread_newcity_activities));
        {
            View view = hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_houses_activities);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        InfoFragment_.this.rlHousesActivities();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_my_messages);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        InfoFragment_.this.rlMyMessages();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_newcity_activities);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        InfoFragment_.this.rlNewcityActivities();
                    }

                }
                );
            }
        }
        afterViews();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public InfoFragment build() {
            InfoFragment_ fragment_ = new InfoFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
