//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande.fragment;

import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import com.movitech.grande.generic.ImageUtils_;
import com.movitech.grande.haerbin.R.layout;
import com.movitech.grande.net.NetHandler_;
import com.movitech.grande.views.LoadDataListView;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class InfoHouseFragment_
    extends InfoHouseFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_info_acitivity, container, false);
        }
        return contentView_;
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        netHandler = NetHandler_.getInstance_(getActivity());
        imageUtils = ImageUtils_.getInstance_(getActivity());
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static InfoHouseFragment_.FragmentBuilder_ builder() {
        return new InfoHouseFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        infoLine = ((View) hasViews.findViewById(com.movitech.grande.haerbin.R.id.info_line));
        lvHouseInfo = ((LoadDataListView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.lv_info));
        afterViews();
    }

    @Override
    public void initSlideViewPage() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                InfoHouseFragment_.super.initSlideViewPage();
            }

        }
        );
    }

    @Override
    public void doBindData() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                InfoHouseFragment_.super.doBindData();
            }

        }
        );
    }

    @Override
    public void switchPage() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                InfoHouseFragment_.super.switchPage();
            }

        }
        );
    }

    @Override
    public void addHouseItems() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                InfoHouseFragment_.super.addHouseItems();
            }

        }
        );
    }

    @Override
    public void loadNewForHouse() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    InfoHouseFragment_.super.loadNewForHouse();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void doLoadData() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    InfoHouseFragment_.super.doLoadData();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public InfoHouseFragment build() {
            InfoHouseFragment_ fragment_ = new InfoHouseFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
