//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande.fragment;

import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.movitech.grande.MainApp_;
import com.movitech.grande.haerbin.R.layout;
import com.movitech.grande.net.NetHandler_;
import com.movitech.grande.views.LoadDataListView;
import com.movitech.grande.views.NoSlideViewPager;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class RecomFragment_
    extends RecomFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_recom, container, false);
        }
        return contentView_;
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        mApp = MainApp_.getInstance();
        netHandler = NetHandler_.getInstance_(getActivity());
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static RecomFragment_.FragmentBuilder_ builder() {
        return new RecomFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        topIndicatorLeft = ((View) hasViews.findViewById(com.movitech.grande.haerbin.R.id.top_indicator_left));
        vpFragmentRecom = ((NoSlideViewPager) hasViews.findViewById(com.movitech.grande.haerbin.R.id.vp_fragment_recom));
        rlTopWordIndicatorAppointment = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_top_word_indicator_appointment));
        puppet = ((View) hasViews.findViewById(com.movitech.grande.haerbin.R.id.puppet));
        rlRecomTab = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_recom_tab));
        ivBack = ((ImageView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.iv_back));
        rlTop = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_top));
        ivAddClient = ((ImageView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.iv_add_client));
        txtTopWordIndicatorAppointment = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_top_word_indicator_appointment));
        lvTeam = ((LoadDataListView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.lv_team));
        rlTeam = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_team));
        topIndicatorRight = ((View) hasViews.findViewById(com.movitech.grande.haerbin.R.id.top_indicator_right));
        rlTopIndicatorExternal = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_top_indicator_external));
        rlTopWordIndicatorRecommend = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_top_word_indicator_recommend));
        txtTopWordIndicatorRecommend = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_top_word_indicator_recommend));
        {
            View view = hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_top_word_indicator_recommend);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        RecomFragment_.this.rlTopWordIndicatorRecommend();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.movitech.grande.haerbin.R.id.iv_add_client);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        RecomFragment_.this.ivAddClient();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_top_word_indicator_appointment);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        RecomFragment_.this.rlTopWordIndicatorAppointment();
                    }

                }
                );
            }
        }
        afterViews();
    }

    @Override
    public void doBindData() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                RecomFragment_.super.doBindData();
            }

        }
        );
    }

    @Override
    public void doLoadDataTeam() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    RecomFragment_.super.doLoadDataTeam();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public RecomFragment build() {
            RecomFragment_ fragment_ = new RecomFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
