//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande.fragment;

import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.movitech.grande.MainApp_;
import com.movitech.grande.haerbin.R.layout;
import com.movitech.grande.net.NetHandler_;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class RecomRecommendFragment_
    extends RecomRecommendFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_recom_recommend, container, false);
        }
        return contentView_;
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        mApp = MainApp_.getInstance();
        netHandler = NetHandler_.getInstance_(getActivity());
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static RecomRecommendFragment_.FragmentBuilder_ builder() {
        return new RecomRecommendFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        edtRemark = ((EditText) hasViews.findViewById(com.movitech.grande.haerbin.R.id.edt_remark));
        txtIntentHouses = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_intent_houses));
        btnRecommendImmediate = ((Button) hasViews.findViewById(com.movitech.grande.haerbin.R.id.btn_recommend_immediate));
        ivContactManRecommended = ((ImageView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.iv_contact_man_recommended));
        rlIntentHouseRight = ((RelativeLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_intent_house_right));
        txtManRecommended = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_man_recommended));
        txtIntentCity = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_intent_city));
        edtContactWay = ((EditText) hasViews.findViewById(com.movitech.grande.haerbin.R.id.edt_contact_way));
        edtIntentCity = ((EditText) hasViews.findViewById(com.movitech.grande.haerbin.R.id.edt_intent_city));
        txtIntentCityUnit = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_intent_city_unit));
        txtContactWay = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_contact_way));
        edtIntentHouses = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.edt_intent_houses));
        txtRemark = ((TextView) hasViews.findViewById(com.movitech.grande.haerbin.R.id.txt_remark));
        edtManRecommended = ((EditText) hasViews.findViewById(com.movitech.grande.haerbin.R.id.edt_man_recommended));
        llSheet = ((LinearLayout) hasViews.findViewById(com.movitech.grande.haerbin.R.id.ll_sheet));
        {
            View view = hasViews.findViewById(com.movitech.grande.haerbin.R.id.rl_intent_house_right);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        RecomRecommendFragment_.this.rlIntentHouseRight();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.movitech.grande.haerbin.R.id.iv_contact_man_recommended);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        RecomRecommendFragment_.this.ivContactManRecommended();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.movitech.grande.haerbin.R.id.edt_intent_district);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        RecomRecommendFragment_.this.edtIntentDistrict();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.movitech.grande.haerbin.R.id.btn_recommend_immediate);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        RecomRecommendFragment_.this.btnRecommendImmediate();
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(com.movitech.grande.haerbin.R.id.edt_intent_city);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        RecomRecommendFragment_.this.edtIntentCity();
                    }

                }
                );
            }
        }
        afterViews();
    }

    @Override
    public void doBindDataRecommended() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                RecomRecommendFragment_.super.doBindDataRecommended();
            }

        }
        );
    }

    @Override
    public void doBindData() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                RecomRecommendFragment_.super.doBindData();
            }

        }
        );
    }

    @Override
    public void addHousesItems() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                RecomRecommendFragment_.super.addHousesItems();
            }

        }
        );
    }

    @Override
    public void doBindDataIntentHouse() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                RecomRecommendFragment_.super.doBindDataIntentHouse();
            }

        }
        );
    }

    @Override
    public void loadNewForHouses() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    RecomRecommendFragment_.super.loadNewForHouses();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void doLoadRecommendedRequest(final String clientName, final String clientPhone, final String recommendedBuilding, final String brokerId, final String recommendMark) {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("queryData", 0, "") {


            @Override
            public void execute() {
                try {
                    RecomRecommendFragment_.super.doLoadRecommendedRequest(clientName, clientPhone, recommendedBuilding, brokerId, recommendMark);
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void queryDistrict() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    RecomRecommendFragment_.super.queryDistrict();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void doLoadDataAndBindDataIntentHouse() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    RecomRecommendFragment_.super.doLoadDataAndBindDataIntentHouse();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public RecomRecommendFragment build() {
            RecomRecommendFragment_ fragment_ = new RecomRecommendFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
