//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande.sp;

import android.content.Context;
import android.content.SharedPreferences;
import org.androidannotations.api.sharedpreferences.BooleanPrefEditorField;
import org.androidannotations.api.sharedpreferences.BooleanPrefField;
import org.androidannotations.api.sharedpreferences.EditorHelper;
import org.androidannotations.api.sharedpreferences.SharedPreferencesHelper;

public final class AppStateSP_
    extends SharedPreferencesHelper
{

    private Context context_;

    public AppStateSP_(Context context) {
        super(context.getSharedPreferences("AppStateSP", 0));
        this.context_ = context;
    }

    public AppStateSP_.AppStateSPEditor_ edit() {
        return new AppStateSP_.AppStateSPEditor_(getSharedPreferences());
    }

    public BooleanPrefField isFirstStartUp() {
        return booleanField("isFirstStartUp", true);
    }

    public final static class AppStateSPEditor_
        extends EditorHelper<AppStateSP_.AppStateSPEditor_>
    {


        AppStateSPEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public BooleanPrefEditorField<AppStateSP_.AppStateSPEditor_> isFirstStartUp() {
            return booleanField("isFirstStartUp");
        }

    }

}
