//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande.sp;

import android.content.Context;
import android.content.SharedPreferences;
import org.androidannotations.api.sharedpreferences.BooleanPrefEditorField;
import org.androidannotations.api.sharedpreferences.BooleanPrefField;
import org.androidannotations.api.sharedpreferences.EditorHelper;
import org.androidannotations.api.sharedpreferences.SharedPreferencesHelper;

public final class LoginSP_
    extends SharedPreferencesHelper
{

    private Context context_;

    public LoginSP_(Context context) {
        super(context.getSharedPreferences("LoginSP", 0));
        this.context_ = context;
    }

    public LoginSP_.LoginSPEditor_ edit() {
        return new LoginSP_.LoginSPEditor_(getSharedPreferences());
    }

    public BooleanPrefField isFirstLogin() {
        return booleanField("isFirstLogin", true);
    }

    public final static class LoginSPEditor_
        extends EditorHelper<LoginSP_.LoginSPEditor_>
    {


        LoginSPEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public BooleanPrefEditorField<LoginSP_.LoginSPEditor_> isFirstLogin() {
            return booleanField("isFirstLogin");
        }

    }

}
