//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande.sp;

import android.content.Context;
import android.content.SharedPreferences;
import org.androidannotations.api.sharedpreferences.EditorHelper;
import org.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import org.androidannotations.api.sharedpreferences.StringPrefEditorField;
import org.androidannotations.api.sharedpreferences.StringPrefField;

public final class NewsSP_
    extends SharedPreferencesHelper
{

    private Context context_;

    public NewsSP_(Context context) {
        super(context.getSharedPreferences("NewsSP", 0));
        this.context_ = context;
    }

    public NewsSP_.NewsSPEditor_ edit() {
        return new NewsSP_.NewsSPEditor_(getSharedPreferences());
    }

    public StringPrefField latestHouseNewsDate() {
        return stringField("latestHouseNewsDate", "0000-00-00 00:00:00");
    }

    public final static class NewsSPEditor_
        extends EditorHelper<NewsSP_.NewsSPEditor_>
    {


        NewsSPEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public StringPrefEditorField<NewsSP_.NewsSPEditor_> latestHouseNewsDate() {
            return stringField("latestHouseNewsDate");
        }

    }

}
