//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande.sp;

import android.content.Context;
import android.content.SharedPreferences;
import org.androidannotations.api.sharedpreferences.EditorHelper;
import org.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import org.androidannotations.api.sharedpreferences.StringPrefEditorField;
import org.androidannotations.api.sharedpreferences.StringPrefField;

public final class ScoreSp_
    extends SharedPreferencesHelper
{

    private Context context_;

    public ScoreSp_(Context context) {
        super(context.getSharedPreferences("ScoreSp", 0));
        this.context_ = context;
    }

    public ScoreSp_.ScoreSpEditor_ edit() {
        return new ScoreSp_.ScoreSpEditor_(getSharedPreferences());
    }

    public StringPrefField signIdAndTime() {
        return stringField("signIdAndTime", "");
    }

    public final static class ScoreSpEditor_
        extends EditorHelper<ScoreSp_.ScoreSpEditor_>
    {


        ScoreSpEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public StringPrefEditorField<ScoreSp_.ScoreSpEditor_> signIdAndTime() {
            return stringField("signIdAndTime");
        }

    }

}
