//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.movitech.grande.sp;

import android.content.Context;
import android.content.SharedPreferences;
import org.androidannotations.api.sharedpreferences.EditorHelper;
import org.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import org.androidannotations.api.sharedpreferences.StringPrefEditorField;
import org.androidannotations.api.sharedpreferences.StringPrefField;

public final class UserSP_
    extends SharedPreferencesHelper
{

    private Context context_;

    public UserSP_(Context context) {
        super(context.getSharedPreferences("UserSP", 0));
        this.context_ = context;
    }

    public UserSP_.UserSPEditor_ edit() {
        return new UserSP_.UserSPEditor_(getSharedPreferences());
    }

    public StringPrefField currBrokerType() {
        return stringField("currBrokerType", "");
    }

    public StringPrefField currPhone() {
        return stringField("currPhone", "");
    }

    public StringPrefField currUserApproveState() {
        return stringField("currUserApproveState", "");
    }

    public StringPrefField currUserCityName() {
        return stringField("currUserCityName", "");
    }

    public StringPrefField currUserId() {
        return stringField("currUserId", "");
    }

    public StringPrefField currUserType() {
        return stringField("currUserType", "");
    }

    public StringPrefField latestUserHeaderSrc() {
        return stringField("latestUserHeaderSrc", "");
    }

    public final static class UserSPEditor_
        extends EditorHelper<UserSP_.UserSPEditor_>
    {


        UserSPEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public StringPrefEditorField<UserSP_.UserSPEditor_> currBrokerType() {
            return stringField("currBrokerType");
        }

        public StringPrefEditorField<UserSP_.UserSPEditor_> currPhone() {
            return stringField("currPhone");
        }

        public StringPrefEditorField<UserSP_.UserSPEditor_> currUserApproveState() {
            return stringField("currUserApproveState");
        }

        public StringPrefEditorField<UserSP_.UserSPEditor_> currUserCityName() {
            return stringField("currUserCityName");
        }

        public StringPrefEditorField<UserSP_.UserSPEditor_> currUserId() {
            return stringField("currUserId");
        }

        public StringPrefEditorField<UserSP_.UserSPEditor_> currUserType() {
            return stringField("currUserType");
        }

        public StringPrefEditorField<UserSP_.UserSPEditor_> latestUserHeaderSrc() {
            return stringField("latestUserHeaderSrc");
        }

    }

}
